---
- name: Deploy local nginx mTLS reverse proxy
  hosts: local
  become: yes
  vars_files:
    - ./vars/cert_path.yml
  
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Enable and start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Remove default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Deploy nginx configs
      template:
        src: http_redirect.conf.j2
        dest: /etc/nginx/conf.d/http.conf

    - name: Deploy frontend
      template:
        src: https_frontend.conf.j2
        dest: /etc/nginx/conf.d/https.conf

    - name: Deploy backend
      template:
        src: backend_mtls.conf.j2
        dest: /etc/nginx/conf.d/backend.conf

    - name: Validate nginx config
      command: nginx -t
      register: nginx_test
      changed_when: false
      failed_when: nginx_test.rc != 0

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded